import {
  defaultCompletedForDate,
  propagateCellInSeries,
  rowsInSeriesFrom,
} from "../../budget/rows";
import { shiftIsoToMonth } from "../../fiscal-month";
import {
  createEmptyRow,
  findColumnByType,
  getStandardColumns,
  mapRowsByIds,
  moveColumn,
  newId,
  updateAccountBudget,
} from "../../sheet";
import { type HintRecording, recordMerchantHints } from "../../merchant-hints";
import { nextUncoveredDate } from "../../coverage";
import type { AccountBudget, Row, UserData } from "../../types";
import type { Action } from "../../reducer";
import type { ItemAction } from "./actions";
import {
  applyPatch,
  applyPatternsAfterCellEdit,
  hintRecordingsFromBudget,
} from "./hints";
import { applyPrimaryIncomeShifts } from "./primary-income";

export type { ItemAction } from "./actions";
export { applyPatternsAfterCellEdit, hintRecordingsFromBudget } from "./hints";

export function reduceAccountBudget(
  item: AccountBudget,
  action: ItemAction,
): AccountBudget {
  switch (action.type) {
    case "updateCell": {
      // The `type` column is a virtual view of `row.typeId` — it has
      // no entry in the row's `cells` map. Route writes into `typeId`
      // directly so the picker, the description chip, and every
      // downstream consumer (modals, merchant hints) read from one
      // source of truth.
      const targetCol = item.columns.find((c) => c.id === action.columnId);
      if (targetCol?.type === "type") {
        return {
          ...item,
          rows: item.rows.map((r) => {
            if (r.id !== action.rowId) return r;
            const next: Row = { ...r };
            if (typeof action.value === "string" && action.value !== "") {
              next.typeId = action.value;
              // Manual type assignment locks the row out of pattern-
              // driven re-labelling: a later description edit shouldn't
              // silently overwrite a label the user chose by hand.
              next.typeIdLocked = true;
            } else {
              delete next.typeId;
              // Clearing the type re-opens the row to pattern matching
              // so the next description commit can pick one up.
              delete next.typeIdLocked;
            }
            return next;
          }),
        };
      }
      return {
        ...item,
        rows: item.rows.map((r) =>
          r.id === action.rowId
            ? { ...r, cells: { ...r.cells, [action.columnId]: action.value } }
            : r,
        ),
      };
    }

    case "toggleRowTransfer": {
      return {
        ...item,
        rows: item.rows.map((r) => {
          if (r.id !== action.rowId) return r;
          if (r.isTransfer) {
            const next = { ...r };
            delete next.isTransfer;
            return next;
          }
          return { ...r, isTransfer: true };
        }),
      };
    }

    case "addRow": {
      const dateCol = findColumnByType(item.columns, "date");
      const date = dateCol && action.date ? action.date : null;
      const newRow: Row = createEmptyRow(item.columns, {
        date,
        completed: defaultCompletedForDate(date),
      });
      return { ...item, rows: [...item.rows, newRow] };
    }

    case "addRowsFromComplex": {
      const { draft } = action;
      // All rows generated by one modal submit share a seriesId so they
      // can be edited or deleted together later.
      const seriesId = draft.dates.length > 1 ? newId() : undefined;
      const newRows: Row[] = draft.dates.map((date) => {
        const row = createEmptyRow(item.columns, {
          date,
          description: draft.description,
          amount: draft.amount,
          completed: defaultCompletedForDate(date),
        });
        if (seriesId) row.seriesId = seriesId;
        if (draft.typeId) {
          row.typeId = draft.typeId;
          // The modal asked the user for a type — treat the choice as
          // an explicit pick so future description edits don't reroute
          // it through pattern matching.
          row.typeIdLocked = true;
        }
        if (draft.companyId) row.companyId = draft.companyId;
        // Formula rows carry the canonical id-keyed form so renames of
        // a referenced sheet don't break the formula; the renderer
        // recomputes the amount each pass via the resolver.
        if (draft.amountFormula) row.amountFormula = draft.amountFormula;
        return row;
      });
      return { ...item, rows: [...item.rows, ...newRows] };
    }

    case "convertToRecurring": {
      const anchor = item.rows.find((r) => r.id === action.rowId);
      if (!anchor) return item;
      // Promote the anchor row into a series of its own. Future rows
      // inherit description and amount from the anchor; the typeId
      // comes from the modal so promotion and type selection happen
      // in the same step.
      const seriesId = anchor.seriesId ?? newId();
      const descCol = findColumnByType(item.columns, "description");
      const amountCol = findColumnByType(item.columns, "amount");
      const newRows: Row[] = action.futureDates.map((date) => {
        const row = createEmptyRow(item.columns, {
          date,
          description:
            descCol && typeof anchor.cells[descCol.id] === "string"
              ? (anchor.cells[descCol.id] as string)
              : "",
          amount:
            amountCol && typeof anchor.cells[amountCol.id] === "number"
              ? (anchor.cells[amountCol.id] as number)
              : 0,
          completed: false,
        });
        row.seriesId = seriesId;
        if (action.typeId) {
          row.typeId = action.typeId;
          row.typeIdLocked = true;
        }
        if (action.companyId) row.companyId = action.companyId;
        return row;
      });
      return {
        ...item,
        rows: [
          ...item.rows.map((r) => {
            if (r.id !== anchor.id) return r;
            const next: Row = { ...r, seriesId };
            if (action.typeId) {
              next.typeId = action.typeId;
              next.typeIdLocked = true;
            } else if (action.typeId === null) {
              delete next.typeId;
              delete next.typeIdLocked;
            }
            if (action.companyId) {
              next.companyId = action.companyId;
            } else if (action.companyId === null) {
              delete next.companyId;
            }
            return next;
          }),
          ...newRows,
        ],
      };
    }

    case "editSeries": {
      const anchor = item.rows.find((r) => r.id === action.rowId);
      if (!anchor) return item;
      const dateCol = findColumnByType(item.columns, "date");
      if (!dateCol) return item;
      const cols = {
        descId: findColumnByType(item.columns, "description")?.id,
        amountId: findColumnByType(item.columns, "amount")?.id,
        dateId: dateCol.id,
      };
      let targets: ReadonlySet<string>;
      if (action.scope.kind === "just-this") {
        targets = new Set([anchor.id]);
      } else if (action.scope.kind === "all") {
        targets = new Set(
          item.rows
            .filter((r) => r.seriesId === anchor.seriesId)
            .map((r) => r.id),
        );
      } else {
        const future = rowsInSeriesFrom(
          item.rows,
          anchor,
          dateCol.id,
          action.scope.untilIso,
        );
        targets = new Set(future.map((r) => r.id));
      }
      return {
        ...item,
        rows: item.rows.map((r) =>
          targets.has(r.id) ? applyPatch(r, action.patch, cols) : r,
        ),
      };
    }

    case "splitRow": {
      const idx = item.rows.findIndex((r) => r.id === action.rowId);
      if (idx < 0) return item;
      const anchor = item.rows[idx];
      const dateCol = findColumnByType(item.columns, "date");
      const completedCol = findColumnByType(item.columns, "completed");
      const amountCol = findColumnByType(item.columns, "amount");
      // Splits inherit the anchor's date and completed state so they
      // land on the same row visually and don't reset a tick-mark the
      // user already set. Description / amount / type come from the
      // submission. Formulas on the anchor are intentionally NOT
      // carried — a split represents the user's concrete allocation,
      // and a formula would re-derive an unrelated amount on the new
      // row.
      const anchorDate =
        dateCol && typeof anchor.cells[dateCol.id] === "string"
          ? (anchor.cells[dateCol.id] as string)
          : null;
      const anchorCompleted =
        completedCol && typeof anchor.cells[completedCol.id] === "boolean"
          ? (anchor.cells[completedCol.id] as boolean)
          : false;
      const splitRows: Row[] = action.splits.map((s) => {
        const r = createEmptyRow(item.columns, {
          date: anchorDate,
          description: s.description,
          amount: s.amount,
          completed: anchorCompleted,
        });
        if (s.typeId) r.typeId = s.typeId;
        if (s.companyId) r.companyId = s.companyId;
        return r;
      });
      // No remainder → the anchor is fully absorbed into the splits
      // and gets removed. Any seriesId, formula, or correction flag on
      // the anchor goes with it; future occurrences of the series stay
      // intact because they're separate rows.
      if (action.remainderAmount === 0) {
        return {
          ...item,
          rows: [
            ...item.rows.slice(0, idx),
            ...splitRows,
            ...item.rows.slice(idx + 1),
          ],
        };
      }
      // Remainder → keep the anchor (so its seriesId / typeId /
      // description survive) but swap its amount for the leftover and
      // push it to the END of the rows array so it appears below the
      // newly-inserted splits on the same date. The anchor may have
      // carried a formula whose cached cell value matched the original
      // amount; we drop the formula here because the rewritten cell is
      // a concrete leftover, not a derived value — keeping the formula
      // would re-derive the original amount on the next render and
      // erase the split.
      const remainderRow: Row = {
        ...anchor,
        cells: amountCol
          ? { ...anchor.cells, [amountCol.id]: action.remainderAmount }
          : { ...anchor.cells },
      };
      delete remainderRow.amountFormula;
      return {
        ...item,
        rows: [
          ...item.rows.slice(0, idx),
          ...splitRows,
          ...item.rows.slice(idx + 1),
          remainderRow,
        ],
      };
    }

    case "propagateCellToFuture": {
      const anchor = item.rows.find((r) => r.id === action.rowId);
      if (!anchor) return item;
      const dateCol = findColumnByType(item.columns, "date");
      if (!dateCol) return item;
      return {
        ...item,
        rows: propagateCellInSeries(
          item.rows,
          anchor,
          dateCol.id,
          action.columnId,
          action.value,
          action.untilIso,
        ),
      };
    }

    case "deleteRows": {
      const drop = new Set(action.rowIds);
      return { ...item, rows: item.rows.filter((r) => !drop.has(r.id)) };
    }

    case "bulkUpdate": {
      const ids = new Set(action.rowIds);
      const { dateCol, amountCol } = getStandardColumns(item.columns);
      return {
        ...item,
        rows: mapRowsByIds(item.rows, ids, (r) => {
          const next: Row = { ...r, cells: { ...r.cells } };
          if (action.patch.date !== undefined && dateCol) {
            next.cells[dateCol.id] = action.patch.date;
          }
          if (action.patch.amount !== undefined && amountCol) {
            next.cells[amountCol.id] = action.patch.amount;
            // Same policy as applyPatch above: a bulk-typed literal
            // replaces any previous formula on the row.
            if (next.amountFormula !== undefined) delete next.amountFormula;
          }
          if (action.patch.typeId !== undefined) {
            if (action.patch.typeId === null) delete next.typeId;
            else next.typeId = action.patch.typeId;
          }
          if (action.patch.companyId !== undefined) {
            if (action.patch.companyId === null) delete next.companyId;
            else next.companyId = action.patch.companyId;
          }
          if (action.patch.isTransfer !== undefined) {
            // Only persist `true` — absent means "not a transfer".
            if (action.patch.isTransfer) next.isTransfer = true;
            else delete next.isTransfer;
          }
          return next;
        }),
      };
    }

    case "bulkShiftToMonth": {
      const { dateCol } = getStandardColumns(item.columns);
      if (!dateCol) return item;
      const ids = new Set(action.rowIds);
      return {
        ...item,
        rows: mapRowsByIds(item.rows, ids, (r) => {
          const cur = r.cells[dateCol.id];
          if (typeof cur !== "string") return r;
          return {
            ...r,
            cells: {
              ...r.cells,
              [dateCol.id]: shiftIsoToMonth(cur, action.targetMonth),
            },
          };
        }),
      };
    }

    case "bulkCopyToMonths": {
      const { dateCol } = getStandardColumns(item.columns);
      if (!dateCol) return item;
      const newRows: Row[] = [];
      for (const r of action.sources) {
        const cur = r.cells[dateCol.id];
        if (typeof cur !== "string") continue;
        for (const month of action.targetMonths) {
          // Copies are independent — drop any seriesId, transferId,
          // historyEntryId, and other runtime-only markers so the new
          // rows live cleanly in `item.rows` without inheriting the
          // source's recurring group or synthesized origin. Type and
          // company tags travel with the copy so the user doesn't have
          // to re-pick them on every duplicated row.
          const next: Row = {
            id: newId(),
            cells: { ...r.cells, [dateCol.id]: shiftIsoToMonth(cur, month) },
          };
          if (r.typeId) next.typeId = r.typeId;
          if (r.companyId) next.companyId = r.companyId;
          newRows.push(next);
        }
      }
      return { ...item, rows: [...item.rows, ...newRows] };
    }

    case "bulkMakeRecurring": {
      const { dateCol } = getStandardColumns(item.columns);
      if (!dateCol) return item;
      const ids = new Set(action.rowIds);
      // Stamp each selected row with a fresh seriesId (preserving an
      // existing one if it already had one), then replicate it at every
      // recurrence date except its own anchor date.
      const updated = mapRowsByIds(item.rows, ids, (r) => ({
        ...r,
        seriesId: r.seriesId ?? newId(),
      }));
      const additions: Row[] = [];
      for (const r of updated) {
        if (!ids.has(r.id)) continue;
        const anchorDate = r.cells[dateCol.id];
        if (typeof anchorDate !== "string") continue;
        for (const date of action.futureDates) {
          if (date === anchorDate) continue;
          const next: Row = {
            id: newId(),
            cells: { ...r.cells, [dateCol.id]: date },
            seriesId: r.seriesId,
          };
          if (r.typeId) next.typeId = r.typeId;
          additions.push(next);
        }
      }
      return { ...item, rows: [...updated, ...additions] };
    }

    case "reorderColumns":
      return {
        ...item,
        columns: moveColumn(item.columns, action.fromId, action.toId),
      };

    case "setRowFiscalMonthShift": {
      let changed = false;
      const rows = item.rows.map((r) => {
        if (r.id !== action.rowId) return r;
        const current = r.fiscalMonthShift;
        if (action.shift === null) {
          if (current === undefined) return r;
          const next = { ...r };
          delete next.fiscalMonthShift;
          changed = true;
          return next;
        }
        if (current === action.shift) return r;
        changed = true;
        return { ...r, fiscalMonthShift: action.shift };
      });
      if (!changed) return item;
      return { ...item, rows };
    }
  }
}

function isItemAction(action: Action): action is ItemAction {
  switch (action.type) {
    case "updateCell":
    case "toggleRowTransfer":
    case "addRow":
    case "addRowsFromComplex":
    case "convertToRecurring":
    case "editSeries":
    case "propagateCellToFuture":
    case "deleteRows":
    case "bulkUpdate":
    case "bulkShiftToMonth":
    case "bulkCopyToMonths":
    case "bulkMakeRecurring":
    case "reorderColumns":
    case "splitRow":
    case "setRowFiscalMonthShift":
      return true;
    default:
      return false;
  }
}

// Item-level dispatch tail. Reduces the targeted sheet, then walks the
// before/after of the targeted AccountBudget to extract any newly-
// assigned categories so the merchant-hint store stays in sync with
// what the user is doing in the grid. Only the touched budget
// contributes recordings; sheets the action didn't reach are
// referentially identical and short-circuit the diff.
//
// Returns null when `action` is not an item action so the outer
// reducer's `??` chain can defer to the next handler.
export function reduceItemDispatch(
  state: UserData,
  action: Action,
): UserData | null {
  if (!isItemAction(action)) return null;
  // Snap date edits forward when the proposed value lands in a
  // calendar month covered by imported history. The bank is
  // authoritative there, so dropping a row into that window would
  // create a false record; nudge the value to the first day of the
  // next uncovered month instead. Applied here (before the
  // sub-reducer runs) so every date-mutating surface — inline cell,
  // edit modal, future drag-to-date — inherits the policy without
  // each having to know about coverage.
  let effectiveAction: ItemAction = action;
  if (action.type === "updateCell") {
    const targetSheet = state.sheets.find((s) => s.id === action.sheetId);
    const targetItem = targetSheet?.items.find(
      (i) => i.id === action.itemId && i.type === "accountBudget",
    ) as AccountBudget | undefined;
    if (targetItem && targetItem.accountId) {
      const col = targetItem.columns.find((c) => c.id === action.columnId);
      if (
        col?.type === "date" &&
        typeof action.value === "string" &&
        action.value.length >= 7
      ) {
        const accountHistory = state.history[targetItem.accountId] ?? [];
        const snapped = nextUncoveredDate(
          action.value,
          accountHistory,
          targetItem.rows,
          targetItem.columns,
          state.settings.startOfMonth,
        );
        if (snapped !== action.value) {
          effectiveAction = { ...action, value: snapped };
        }
      }
    }
  }
  const recordings: HintRecording[] = [];
  const sheets = updateAccountBudget(
    state.sheets,
    action.sheetId,
    action.itemId,
    (item) => {
      const reduced = reduceAccountBudget(item, effectiveAction);
      if (reduced === item) return item;
      // Apply pattern-driven typeIds AFTER the sub-reducer runs so
      // every cell-mutating action (inline edit, edit modal, complex
      // add, recurring promote) inherits the same auto-labelling
      // policy without each having to know about matchRules. The
      // hint-recording pass below then sees the post-pattern shape so
      // a freshly auto-assigned type also feeds the merchant memory.
      const labelled = applyPatternsAfterCellEdit(
        item,
        reduced,
        state.matchRules,
      );
      // Re-stamp `fiscalMonthShift` on every row in a primary-income
      // series whose date may have just changed. Cheap walk because
      // the metadata map is small (typically one entry); skips items
      // entirely when no series is flagged. Done here so adding a row
      // (`addRowsFromComplex`), editing one (`editSeries`,
      // `updateCell` on the date column), or promoting candidates all
      // pick up the cascade without each path repeating the logic.
      const next = applyPrimaryIncomeShifts(labelled, state.seriesMetadata);
      recordings.push(...hintRecordingsFromBudget(item, next));
      // "Make recurring" should also backfill the user-typed
      // description onto past bank-history entries whose normalised
      // text matches the row — the `hintRecordingsFromBudget` diff
      // above carries the typeId, but the merchant-hint's
      // `description_override` only stamps when the recording
      // explicitly sets it. Emit one targeted recording from the
      // anchor row so synthesized history rows render the clean
      // label ("Spotify") rather than the raw bank text
      // ("*SPOTIFY P12AB34"). Skipped when the user declined a type
      // — the override would otherwise stick without a category to
      // route the past entries under.
      if (
        effectiveAction.type === "convertToRecurring" &&
        effectiveAction.typeId
      ) {
        const descCol = findColumnByType(item.columns, "description");
        const anchor = item.rows.find((r) => r.id === effectiveAction.rowId);
        if (descCol && anchor) {
          const desc = anchor.cells[descCol.id];
          if (typeof desc === "string" && desc.trim() !== "") {
            recordings.push({
              description: desc,
              typeId: effectiveAction.typeId,
              description_override: desc,
              // Fold the company tag into the merchant hint so past
              // synthesized rows sharing this merchant key adopt it
              // alongside the description / type overlay.
              companyId: effectiveAction.companyId ?? undefined,
            });
          }
        }
      }
      return next;
    },
  );
  const next = sheets === state.sheets ? state : { ...state, sheets };
  return recordMerchantHints(next, recordings, Date.now());
}
