import {
  AlignLeft,
  ArrowDownCircle,
  ArrowUpCircle,
  Baby,
  Banknote,
  Bed,
  Beer,
  Bike,
  Bitcoin,
  BookOpen,
  Briefcase,
  BrushCleaning,
  Building2,
  Bus,
  Cake,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Cat,
  Check,
  Coffee,
  Coins,
  Cookie,
  CookingPot,
  CreditCard,
  Dog,
  DollarSign,
  Droplet,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HandCoins,
  HandHeart,
  HandPlatter,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hotel,
  IceCream,
  Key,
  Landmark,
  Laptop,
  Lightbulb,
  LineChart,
  Music,
  Package,
  PawPrint,
  PieChart,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Scale,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Tag,
  Ticket,
  Train,
  Trash2,
  TreePine,
  TrendingUp,
  Umbrella,
  Utensils,
  Vault,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";
import type { CSSProperties } from "react";

import type { CategoryIcon, ColumnType } from "../data/types";

const COLUMN_ICONS: Record<ColumnType, typeof Calendar> = {
  date: Calendar,
  description: AlignLeft,
  type: Tag,
  amount: DollarSign,
  balance: Wallet,
  completed: Check,
};

export function ColumnIcon({
  type,
  size = 16,
  className,
}: {
  type: ColumnType;
  size?: number;
  className?: string;
}) {
  const Icon = COLUMN_ICONS[type];
  return (
    <Icon size={size} className={className} aria-hidden focusable={false} />
  );
}

const CATEGORY_ICONS: Record<CategoryIcon, typeof Tag> = {
  tag: Tag,
  home: Home,
  car: Car,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  heart: Heart,
  gift: Gift,
  music: Music,
  film: Film,
  plane: Plane,
  hotel: Hotel,
  package: Package,
  "hand-heart": HandHeart,
  briefcase: Briefcase,
  "graduation-cap": GraduationCap,
  stethoscope: Stethoscope,
  pill: Pill,
  receipt: Receipt,
  banknote: Banknote,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  wallet: Wallet,
  zap: Zap,
  sparkles: Sparkles,
  star: Star,
  cookie: Cookie,
  cake: Cake,
  "ice-cream": IceCream,
  beer: Beer,
  wine: Wine,
  "hand-platter": HandPlatter,
  "cooking-pot": CookingPot,
  bus: Bus,
  train: Train,
  bike: Bike,
  fuel: Fuel,
  bed: Bed,
  sofa: Sofa,
  lightbulb: Lightbulb,
  droplet: Droplet,
  flame: Flame,
  wifi: Wifi,
  key: Key,
  wrench: Wrench,
  hammer: Hammer,
  "brush-cleaning": BrushCleaning,
  "trash-2": Trash2,
  sprout: Sprout,
  umbrella: Umbrella,
  smartphone: Smartphone,
  laptop: Laptop,
  headphones: Headphones,
  camera: Camera,
  shirt: Shirt,
  scissors: Scissors,
  ticket: Ticket,
  "gamepad-2": Gamepad2,
  "book-open": BookOpen,
  dumbbell: Dumbbell,
  dog: Dog,
  cat: Cat,
  "paw-print": PawPrint,
  "tree-pine": TreePine,
  baby: Baby,
  "heart-pulse": HeartPulse,
  coins: Coins,
  "hand-coins": HandCoins,
  landmark: Landmark,
  "building-2": Building2,
  vault: Vault,
  gem: Gem,
  bitcoin: Bitcoin,
  scale: Scale,
  "trending-up": TrendingUp,
  "line-chart": LineChart,
  "pie-chart": PieChart,
  "calendar-days": CalendarDays,
  globe: Globe,
  "arrow-down-circle": ArrowDownCircle,
  "arrow-up-circle": ArrowUpCircle,
};

export function CategoryIconGlyph({
  name,
  size = 14,
  className,
  style,
}: {
  name: CategoryIcon;
  size?: number;
  className?: string;
  style?: CSSProperties;
}) {
  const Icon = CATEGORY_ICONS[name];
  return (
    <Icon
      size={size}
      className={className}
      style={style}
      aria-hidden
      focusable={false}
    />
  );
}
