import {
  AlignLeft,
  ArrowDownCircle,
  ArrowUpCircle,
  Atom,
  Baby,
  Banknote,
  BanknoteArrowDown,
  Bath,
  BatteryCharging,
  Bed,
  Beer,
  Bike,
  Bitcoin,
  BookHeadphones,
  BookMarked,
  BookOpen,
  Brain,
  Briefcase,
  BrushCleaning,
  Building2,
  Bus,
  Cake,
  Calendar,
  CalendarDays,
  Camera,
  Candy,
  Car,
  CarFront,
  Cat,
  ChartCandlestick,
  Check,
  CircleHelp,
  Clapperboard,
  Cloud,
  Coffee,
  Coins,
  Compass,
  Cookie,
  CookingPot,
  Cpu,
  Croissant,
  CreditCard,
  Crown,
  Diamond,
  Dice5,
  Dna,
  Dog,
  DollarSign,
  Drill,
  Droplet,
  Dumbbell,
  Factory,
  Film,
  Flag,
  Flame,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  HandCoins,
  HandHeart,
  HandPlatter,
  Handshake,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hotel,
  Hourglass,
  IceCream,
  Key,
  Lamp,
  Landmark,
  Laptop,
  Lightbulb,
  LineChart,
  Medal,
  Microscope,
  Milk,
  Music,
  Newspaper,
  Package,
  PaintRoller,
  Palette,
  PawPrint,
  Pencil,
  Percent,
  Pickaxe,
  PieChart,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Repeat,
  Rocket,
  Satellite,
  Scale,
  School,
  Scissors,
  ScrollText,
  Ship,
  Shield,
  ShieldAlert,
  ShieldPlus,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Ticket,
  ToyBrick,
  Train,
  Trash2,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  Vault,
  Wallet,
  WashingMachine,
  Watch,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";
import type { CSSProperties } from "react";

import type { CategoryIcon, ColumnType } from "../data/types";

const COLUMN_ICONS: Record<ColumnType, typeof Calendar> = {
  date: Calendar,
  description: AlignLeft,
  type: Tag,
  amount: DollarSign,
  balance: Wallet,
  completed: Check,
};

export function ColumnIcon({
  type,
  size = 16,
  className,
}: {
  type: ColumnType;
  size?: number;
  className?: string;
}) {
  const Icon = COLUMN_ICONS[type];
  return (
    <Icon size={size} className={className} aria-hidden focusable={false} />
  );
}

const CATEGORY_ICONS: Record<CategoryIcon, typeof Tag> = {
  tag: Tag,
  home: Home,
  car: Car,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  heart: Heart,
  gift: Gift,
  music: Music,
  film: Film,
  plane: Plane,
  hotel: Hotel,
  package: Package,
  "hand-heart": HandHeart,
  briefcase: Briefcase,
  "graduation-cap": GraduationCap,
  stethoscope: Stethoscope,
  pill: Pill,
  receipt: Receipt,
  banknote: Banknote,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  wallet: Wallet,
  zap: Zap,
  sparkles: Sparkles,
  star: Star,
  cookie: Cookie,
  croissant: Croissant,
  cake: Cake,
  "ice-cream": IceCream,
  candy: Candy,
  beer: Beer,
  wine: Wine,
  "hand-platter": HandPlatter,
  "cooking-pot": CookingPot,
  milk: Milk,
  bus: Bus,
  train: Train,
  bike: Bike,
  fuel: Fuel,
  "car-front": CarFront,
  ship: Ship,
  bed: Bed,
  sofa: Sofa,
  lightbulb: Lightbulb,
  droplet: Droplet,
  flame: Flame,
  wifi: Wifi,
  key: Key,
  wrench: Wrench,
  hammer: Hammer,
  drill: Drill,
  "brush-cleaning": BrushCleaning,
  "trash-2": Trash2,
  sprout: Sprout,
  umbrella: Umbrella,
  "paint-roller": PaintRoller,
  "washing-machine": WashingMachine,
  smartphone: Smartphone,
  laptop: Laptop,
  headphones: Headphones,
  camera: Camera,
  tv: Tv,
  watch: Watch,
  shirt: Shirt,
  scissors: Scissors,
  ticket: Ticket,
  "gamepad-2": Gamepad2,
  "book-open": BookOpen,
  dumbbell: Dumbbell,
  dog: Dog,
  cat: Cat,
  "paw-print": PawPrint,
  "tree-pine": TreePine,
  baby: Baby,
  "toy-brick": ToyBrick,
  school: School,
  trophy: Trophy,
  pencil: Pencil,
  "dice-5": Dice5,
  "book-headphones": BookHeadphones,
  hourglass: Hourglass,
  "heart-pulse": HeartPulse,
  "shield-plus": ShieldPlus,
  glasses: Glasses,
  brain: Brain,
  coins: Coins,
  "hand-coins": HandCoins,
  landmark: Landmark,
  "building-2": Building2,
  vault: Vault,
  gem: Gem,
  bitcoin: Bitcoin,
  scale: Scale,
  "trending-up": TrendingUp,
  "line-chart": LineChart,
  "pie-chart": PieChart,
  "calendar-days": CalendarDays,
  globe: Globe,
  "arrow-down-circle": ArrowDownCircle,
  "arrow-up-circle": ArrowUpCircle,
  percent: Percent,
  "scroll-text": ScrollText,
  newspaper: Newspaper,
  "book-marked": BookMarked,
  clapperboard: Clapperboard,
  guitar: Guitar,
  palette: Palette,
  lamp: Lamp,
  bath: Bath,
  compass: Compass,
  user: User,
  users: Users,
  handshake: Handshake,
  "circle-help": CircleHelp,
  repeat: Repeat,
  "banknote-arrow-down": BanknoteArrowDown,
  flag: Flag,
  "shield-alert": ShieldAlert,
  cloud: Cloud,
  "chart-candlestick": ChartCandlestick,
  diamond: Diamond,
  crown: Crown,
  medal: Medal,
  cpu: Cpu,
  satellite: Satellite,
  rocket: Rocket,
  dna: Dna,
  microscope: Microscope,
  sun: Sun,
  wind: Wind,
  atom: Atom,
  "battery-charging": BatteryCharging,
  factory: Factory,
  pickaxe: Pickaxe,
  wheat: Wheat,
  truck: Truck,
  shield: Shield,
};

export function CategoryIconGlyph({
  name,
  size = 14,
  className,
  style,
}: {
  name: CategoryIcon;
  size?: number;
  className?: string;
  style?: CSSProperties;
}) {
  const Icon = CATEGORY_ICONS[name];
  return (
    <Icon
      size={size}
      className={className}
      style={style}
      aria-hidden
      focusable={false}
    />
  );
}
