// Build-time parser: reads /CHANGELOG.md, emits
// src/generated/changelog.ts as the typed `CHANGELOG` constant the app
// renders inside the changelog / "What's new" modal. Runs on
// `buildStart` so a malformed CHANGELOG fails the build fast; the dev
// server watches the source so edits surface without a restart.
//
// Types are emitted inline into the generated file rather than imported
// from this module so `src/` code stays inside `tsconfig.app.json` and
// doesn't have to reach into the `vite/` tsconfig.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import type { Plugin } from "vite";

export type ChangelogEntryType =
  | "Added"
  | "Changed"
  | "Fixed"
  | "Removed"
  | "Security"
  | "Deprecated";

export interface ChangelogSection {
  type: ChangelogEntryType;
  items: string[];
}

export interface ChangelogRelease {
  // "Unreleased" or a semver like "0.1.0". The version-vs-version
  // comparison the app does for the "What's new" modal skips
  // "Unreleased".
  version: string;
  // ISO date (YYYY-MM-DD) the release went out, or null for Unreleased.
  date: string | null;
  sections: ChangelogSection[];
}

const VERSION_RE = /^## \[([^\]]+)\](?:\s*[-—–]\s*(\d{4}-\d{2}-\d{2}))?/;
const SECTION_RE = /^### (Added|Changed|Fixed|Removed|Security|Deprecated)\s*$/;
const TYPES: ReadonlySet<ChangelogEntryType> = new Set([
  "Added",
  "Changed",
  "Fixed",
  "Removed",
  "Security",
  "Deprecated",
]);

export function parseChangelog(md: string): ChangelogRelease[] {
  const releases: ChangelogRelease[] = [];
  let curRelease: ChangelogRelease | null = null;
  let curSection: ChangelogSection | null = null;
  let bullet: string[] = [];

  const flushBullet = () => {
    if (bullet.length && curSection) {
      curSection.items.push(bullet.join("\n").trim());
    }
    bullet = [];
  };
  const flushSection = () => {
    flushBullet();
    if (curSection && curRelease) curRelease.sections.push(curSection);
    curSection = null;
  };
  const flushRelease = () => {
    flushSection();
    if (curRelease) releases.push(curRelease);
    curRelease = null;
  };

  for (const line of md.split("\n")) {
    const vm = VERSION_RE.exec(line);
    if (vm) {
      flushRelease();
      curRelease = {
        version: vm[1],
        date: vm[2] ?? null,
        sections: [],
      };
      continue;
    }
    const sm = SECTION_RE.exec(line);
    if (sm) {
      flushSection();
      const t = sm[1] as ChangelogEntryType;
      if (TYPES.has(t)) curSection = { type: t, items: [] };
      continue;
    }
    if (!curRelease) continue;
    if (/^- /.test(line)) {
      flushBullet();
      bullet = [line.replace(/^- /, "")];
      continue;
    }
    if (/^\s+\S/.test(line) && bullet.length) {
      bullet.push(line.trim());
      continue;
    }
    if (line.trim() === "") {
      flushBullet();
      continue;
    }
  }
  flushRelease();
  // Drop the "[Unreleased]" stub when it has no bullets — keeps the
  // app's changelog list tidy between releases.
  return releases.filter(
    (r) => !(r.version === "Unreleased" && r.sections.length === 0),
  );
}

function renderGenerated(data: readonly ChangelogRelease[]): string {
  return (
    `// AUTO-GENERATED by vite/changelog-plugin.ts from /CHANGELOG.md.\n` +
    `// Do not edit by hand — re-run \`make build\` (or restart the dev\n` +
    `// server) after editing CHANGELOG.md.\n\n` +
    `export type ChangelogEntryType =\n` +
    `  | "Added"\n  | "Changed"\n  | "Fixed"\n` +
    `  | "Removed"\n  | "Security"\n  | "Deprecated";\n\n` +
    `export interface ChangelogSection {\n` +
    `  type: ChangelogEntryType;\n  items: string[];\n}\n\n` +
    `export interface ChangelogRelease {\n` +
    `  version: string;\n  date: string | null;\n` +
    `  sections: ChangelogSection[];\n}\n\n` +
    `export const CHANGELOG: readonly ChangelogRelease[] = ${JSON.stringify(
      data,
      null,
      2,
    )} as const;\n`
  );
}

export function emitChangelogData(): Plugin {
  const src = resolve(__dirname, "..", "CHANGELOG.md");
  const out = resolve(__dirname, "..", "src", "generated", "changelog.ts");

  const write = () => {
    if (!existsSync(src)) {
      // Edge case: a fresh checkout without CHANGELOG.md (shouldn't
      // happen in this repo). Emit an empty list rather than crashing
      // the dev server.
      mkdirSync(dirname(out), { recursive: true });
      writeFileSync(out, renderGenerated([]), "utf8");
      return;
    }
    const md = readFileSync(src, "utf8");
    const data = parseChangelog(md);
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, renderGenerated(data), "utf8");
  };

  return {
    name: "emit-changelog-data",
    buildStart() {
      write();
    },
    configureServer(server) {
      // Emit once at dev-server start so the generated file exists,
      // then re-emit on every change so HMR picks up new entries
      // without restart.
      write();
      server.watcher.add(src);
      server.watcher.on("change", (path) => {
        if (path === src) write();
      });
    },
  };
}
