// Build-time bundler for feature docs: reads every `docs/features/*.md`
// and emits `src/generated/feature-docs.ts` as the typed `FEATURE_DOCS`
// record the changelog modal reads when a "Learn more" link is followed.
// Mirrors `vite/changelog-plugin.ts`: runs on `buildStart` so a missing
// docs directory degrades to an empty record rather than crashing, and
// the dev server watches the source so edits surface without a restart.
//
// The app is a static bundle with no backend, so feature docs can't be
// fetched at runtime — they're inlined into the bundle here. They're
// English-only, like the rendered CHANGELOG body (see the "What's
// intentionally not translated" note in AGENTS.md).

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";

import type { Plugin } from "vite";

export interface FeatureDoc {
  // Filename stem (`docs/features/<slug>.md`) — also the `feature:<slug>`
  // link target authored in changelog fragments / CHANGELOG.md.
  slug: string;
  // First `# ` heading in the file, used as the modal's doc-view title.
  title: string;
  // Everything after that heading — the markdown the modal renders.
  body: string;
}

// Split a doc into its title (the leading `# ` heading) and body. The
// heading is consumed so the modal can render it in the header chrome
// without it repeating at the top of the scrolling body. Falls back to
// the slug when a doc has no leading heading.
export function parseFeatureDoc(slug: string, md: string): FeatureDoc {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  let start = 0;
  while (start < lines.length && lines[start].trim() === "") start++;
  let title = slug;
  const h1 = /^#\s+(.*)$/.exec(lines[start] ?? "");
  if (h1) {
    title = h1[1].trim();
    start++;
  }
  return { slug, title, body: lines.slice(start).join("\n").trim() };
}

export function collectFeatureDocs(dir: string): FeatureDoc[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((n) => n.endsWith(".md") && !n.startsWith("."))
    .sort()
    .map((name) => {
      const slug = name.replace(/\.md$/, "");
      return parseFeatureDoc(slug, readFileSync(join(dir, name), "utf8"));
    });
}

export function renderFeatureDocs(docs: readonly FeatureDoc[]): string {
  const record = Object.fromEntries(docs.map((d) => [d.slug, d]));
  return (
    `// AUTO-GENERATED by vite/feature-docs-plugin.ts (and the standalone\n` +
    `// scripts/codegen/feature-docs.mjs) from docs/features/*.md.\n` +
    `// Do not edit by hand — re-run \`make codegen\` (or restart the dev\n` +
    `// server) after editing a feature doc.\n\n` +
    `export interface FeatureDoc {\n` +
    `  slug: string;\n  title: string;\n  body: string;\n}\n\n` +
    `export const FEATURE_DOCS: Record<string, FeatureDoc> = ${JSON.stringify(
      record,
      null,
      2,
    )};\n`
  );
}

export function emitFeatureDocs(): Plugin {
  const srcDir = resolve(__dirname, "..", "docs", "features");
  const out = resolve(__dirname, "..", "src", "generated", "feature-docs.ts");

  const write = () => {
    const docs = collectFeatureDocs(srcDir);
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, renderFeatureDocs(docs), "utf8");
  };

  return {
    name: "emit-feature-docs",
    buildStart() {
      write();
    },
    configureServer(server) {
      write();
      server.watcher.add(srcDir);
      const onChange = (path: string) => {
        if (path.startsWith(srcDir)) write();
      };
      server.watcher.on("change", onChange);
      server.watcher.on("add", onChange);
      server.watcher.on("unlink", onChange);
    },
  };
}
