#!/usr/bin/env node
// Standalone codegen: read CHANGELOG.md, write src/generated/changelog.ts.
//
// Mirrors what `vite/changelog-plugin.ts` does at `buildStart`, but as a
// plain `node` invocation so the Makefile can run it BEFORE `tsc -b
// --noEmit` (typecheck). Without this, CI's `make lint` step trips on
// ChangelogPage / ChangelogModal importing from `../generated/changelog`
// — that file doesn't exist on a fresh checkout because the directory
// is gitignored.
//
// Two parsers (here and in the Vite plugin) is mild duplication, but
// the Keep-a-Changelog format is stable and both implementations
// produce byte-identical output for the same input. Tests / spot-
// checks catch drift if it ever happens.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = resolve(dirname(__filename), "..", "..");
const SRC = resolve(REPO_ROOT, "CHANGELOG.md");
const OUT = resolve(REPO_ROOT, "src", "generated", "changelog.ts");

const VERSION_RE = /^## \[([^\]]+)\](?:\s*[-—–]\s*(\d{4}-\d{2}-\d{2}))?/;
const SECTION_RE = /^### (Added|Changed|Fixed|Removed|Security|Deprecated)\s*$/;
const TYPES = new Set([
  "Added",
  "Changed",
  "Fixed",
  "Removed",
  "Security",
  "Deprecated",
]);

function parseChangelog(md) {
  const releases = [];
  let curRelease = null;
  let curSection = null;
  let bullet = [];

  const flushBullet = () => {
    if (bullet.length && curSection) {
      curSection.items.push(bullet.join("\n").trim());
    }
    bullet = [];
  };
  const flushSection = () => {
    flushBullet();
    if (curSection && curRelease) curRelease.sections.push(curSection);
    curSection = null;
  };
  const flushRelease = () => {
    flushSection();
    if (curRelease) releases.push(curRelease);
    curRelease = null;
  };

  for (const line of md.split("\n")) {
    const vm = VERSION_RE.exec(line);
    if (vm) {
      flushRelease();
      curRelease = { version: vm[1], date: vm[2] ?? null, sections: [] };
      continue;
    }
    const sm = SECTION_RE.exec(line);
    if (sm) {
      flushSection();
      if (TYPES.has(sm[1])) curSection = { type: sm[1], items: [] };
      continue;
    }
    if (!curRelease) continue;
    if (/^- /.test(line)) {
      flushBullet();
      bullet = [line.replace(/^- /, "")];
      continue;
    }
    if (/^\s+\S/.test(line) && bullet.length) {
      bullet.push(line.trim());
      continue;
    }
    if (line.trim() === "") {
      flushBullet();
      continue;
    }
  }
  flushRelease();
  return releases.filter(
    (r) => !(r.version === "Unreleased" && r.sections.length === 0),
  );
}

function renderGenerated(data) {
  return (
    `// AUTO-GENERATED by scripts/codegen/changelog.mjs from /CHANGELOG.md.\n` +
    `// Do not edit by hand — re-run \`make codegen\` (or any of the\n` +
    `// targets that depend on it: typecheck / lint / build) after\n` +
    `// editing CHANGELOG.md.\n\n` +
    `export type ChangelogEntryType =\n` +
    `  | "Added"\n  | "Changed"\n  | "Fixed"\n` +
    `  | "Removed"\n  | "Security"\n  | "Deprecated";\n\n` +
    `export interface ChangelogSection {\n` +
    `  type: ChangelogEntryType;\n  items: string[];\n}\n\n` +
    `export interface ChangelogRelease {\n` +
    `  version: string;\n  date: string | null;\n` +
    `  sections: ChangelogSection[];\n}\n\n` +
    `export const CHANGELOG: readonly ChangelogRelease[] = ${JSON.stringify(
      data,
      null,
      2,
    )} as const;\n`
  );
}

const md = existsSync(SRC) ? readFileSync(SRC, "utf8") : "";
const data = parseChangelog(md);
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, renderGenerated(data), "utf8");
console.log(
  `Wrote ${OUT.replace(REPO_ROOT + "/", "")} from ${data.length} release(s).`,
);
