#!/usr/bin/env node
// Standalone codegen: read docs/features/*.md, write
// src/generated/feature-docs.ts.
//
// Mirrors what `vite/feature-docs-plugin.ts` does at `buildStart`, but as
// a plain `node` invocation so the Makefile can run it BEFORE `tsc -b
// --noEmit` (typecheck). Without this, CI's `make lint` step trips on
// ChangelogModal importing from `../generated/feature-docs` — that file
// doesn't exist on a fresh checkout because the directory is gitignored.
//
// Two parsers (here and in the Vite plugin) is mild duplication, matching
// the changelog codegen pair. The format is trivial and both produce
// byte-identical output for the same input.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = resolve(dirname(__filename), "..", "..");
const SRC_DIR = resolve(REPO_ROOT, "docs", "features");
const OUT = resolve(REPO_ROOT, "src", "generated", "feature-docs.ts");

function parseFeatureDoc(slug, md) {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  let start = 0;
  while (start < lines.length && lines[start].trim() === "") start++;
  let title = slug;
  const h1 = /^#\s+(.*)$/.exec(lines[start] ?? "");
  if (h1) {
    title = h1[1].trim();
    start++;
  }
  return { slug, title, body: lines.slice(start).join("\n").trim() };
}

function collectFeatureDocs(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((n) => n.endsWith(".md") && !n.startsWith("."))
    .sort()
    .map((name) => {
      const slug = name.replace(/\.md$/, "");
      return parseFeatureDoc(slug, readFileSync(join(dir, name), "utf8"));
    });
}

function renderFeatureDocs(docs) {
  const record = Object.fromEntries(docs.map((d) => [d.slug, d]));
  return (
    `// AUTO-GENERATED by vite/feature-docs-plugin.ts (and the standalone\n` +
    `// scripts/codegen/feature-docs.mjs) from docs/features/*.md.\n` +
    `// Do not edit by hand — re-run \`make codegen\` (or restart the dev\n` +
    `// server) after editing a feature doc.\n\n` +
    `export interface FeatureDoc {\n` +
    `  slug: string;\n  title: string;\n  body: string;\n}\n\n` +
    `export const FEATURE_DOCS: Record<string, FeatureDoc> = ${JSON.stringify(
      record,
      null,
      2,
    )};\n`
  );
}

const docs = collectFeatureDocs(SRC_DIR);
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, renderFeatureDocs(docs), "utf8");
console.log(
  `Wrote ${OUT.replace(REPO_ROOT + "/", "")} from ${docs.length} feature doc(s).`,
);
